name: CI/CD for Dockerize FastAPI app

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        
jobs:
    build-and-test: # For Unit testing
        runs-on: ubuntu-latest 


        steps:
        - name: Checkout code
          uses: actions/checkout@v3    
        
        - name: Set Up Python
          uses: actions/setup-python@v4  
          with:
            python-version: '3.9'

        - name: Install Dependencies
          run: 
            python -m pip install --upgrade pip
            pip install fastapi[standard]
            pip install pytest
        - name: Run Tests
          run:
            pytest 


    build-and-publish: # Building and Pushing Docker to Hub
        needs: build-and-test
        runs-on: ubuntu-latest 


        steps:
        - name: Checkout code
          uses: actions/checkout@v3    
        
        - name: Set Up Docker Build
          uses: docker/setup-buildx-action@v2  

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME}}
            password: ${{ secrets.DOCKER_PASSWORD}}






